### ISSUE TITLE
Nest test plans

### ISSUE THREAD

**Issue by kanaikimi** [StepQA/StepQA#15]
As a tester, so I can reuse and have a single plan for testing a feature/path, I want to nest/reference an existing test plan inside of another test plan.

**Comment by elmarti** [comment]
https://trello.com/c/dQyKN1m1

**Comment by elmarti** [comment]
Now possible to do this by drag selecting rows within the test builder. Still need to add functionality for test imports.

**Comment by elmarti** [comment]
Functionality still to implement:

-  rows highlight on hover and show pointer cursor. Clicking should allow users to embed a test

**Comment by elmarti** [comment]
This is being moved to the beta period; it won't preview MVP release, but makes the builder a bit more cumbersome.

**Comment by elmarti** [comment]
This was implemented, not sure how I didn't catch this
