### ISSUE TITLE
Create Tests button hidden away

### ISSUE THREAD

**Issue by lewishinshelwood** [StepQA/StepQA#7]
The + button on the tests page needs to be bigger and more obvious
![image](https://user-images.githubusercontent.com/39331904/40108199-2bdf5b28-58f2-11e8-946f-8a0cbe21fea4.png)

**Comment by elmarti** [comment]
This is now done at the very highest level - there is a create test button in the top nav bar. 

The modal dialog that shows will need some more work to have some awareness of the context ie - the user is working on a group A project and clicks "Create test". The selected group should be defaulted to the group that owns the current project.
